import os
from pathlib import Path

configfile: "config.yaml"


def read_accessions(path: str) -> list[str]:
    with open(path) as f:
        return [l.strip() for l in f if l.strip() and not l.startswith("#")]


# ------------------------------------------------------------------
# Inputs: ONLY config.yaml + accessions.txt are required on a clean clone
# ------------------------------------------------------------------
ACCESSIONS = read_accessions(config["accessions_file"])
SAMPLES = ACCESSIONS  # sample IDs == run accessions in this project


# ------------------------------------------------------------------
# FASTQs and samples table (generated by scripts/download_fastq.sh)
# ------------------------------------------------------------------
FASTQ_R1 = expand(
    "{fastq_dir}/{sample}_1.fastq.gz",
    fastq_dir=config["fastq_dir"],
    sample=SAMPLES,
)
FASTQ_R2 = expand(
    "{fastq_dir}/{sample}_2.fastq.gz",
    fastq_dir=config["fastq_dir"],
    sample=SAMPLES,
)


# ------------------------------------------------------------------
# Reference (raw + canonical)
# ------------------------------------------------------------------
REF_DIR = config["reference_dir"]
REF_FILE = config["references"][0].replace(".gz", "")
CANON_FILE = config.get("reference_canonical", [REF_FILE])[0]

REF_FA = os.path.join(REF_DIR, REF_FILE)
CANON_FA = os.path.join(REF_DIR, CANON_FILE)

REF_FAIDX = [REF_FA + ".fai", CANON_FA + ".fai"]
REF_DICT = [
    os.path.join(REF_DIR, Path(REF_FILE).with_suffix("").with_suffix(".dict").name),
    os.path.join(REF_DIR, Path(CANON_FILE).with_suffix("").with_suffix(".dict").name),
]

BWA_INDEX = [CANON_FA + ext for ext in [".amb", ".ann", ".bwt", ".pac", ".sa"]]


# ------------------------------------------------------------------
# BAM outputs
# ------------------------------------------------------------------
BAM_DIR = config.get("bam_dir", "results/bam")
Path(BAM_DIR).mkdir(parents=True, exist_ok=True)

SAMS = expand(
    os.path.join(BAM_DIR, "{sample}.sam"),
    sample=SAMPLES,
)

SORTED_BAMS = expand(
    os.path.join(BAM_DIR, "{sample}.sorted.bam"),
    sample=SAMPLES,
)


# ------------------------------------------------------------------
# Metrics outputs
# ------------------------------------------------------------------
METRICS_DIR = config.get("metrics_dir", "results/metrics")
Path(METRICS_DIR).mkdir(parents=True, exist_ok=True)

METRICS = expand(
    os.path.join(METRICS_DIR, "{sample}.alignment_metrics.txt"),
    sample=SAMPLES,
)


# ------------------------------------------------------------------
# Dedup + index outputs
# ------------------------------------------------------------------
DEDUP_DIR = config.get("dedup_dir", "results/dedup")
Path(DEDUP_DIR).mkdir(parents=True, exist_ok=True)

DEDUP_BAMS = expand(
    os.path.join(DEDUP_DIR, "{sample}.dedup.bam"),
    sample=SAMPLES,
)
DEDUP_METRICS = expand(
    os.path.join(DEDUP_DIR, "{sample}.metrics.txt"),
    sample=SAMPLES,
)
DEDUP_BAI = expand(
    os.path.join(DEDUP_DIR, "{sample}.dedup.bai"),
    sample=SAMPLES,
)


# ------------------------------------------------------------------
# Step 4 — Call Variants (GATK4 HaplotypeCaller)
# ------------------------------------------------------------------
VCF_DIR = config.get("vcf_dir", "results/vcfs")
Path(VCF_DIR).mkdir(parents=True, exist_ok=True)

RAW_VCFS = expand(
    os.path.join(VCF_DIR, "{sample}.raw_variants.vcf"),
    sample=SAMPLES,
)
RAW_VCF_IDXS = [v + ".idx" for v in RAW_VCFS]


# ------------------------------------------------------------------
# Step 5 — Split Variants (SNP vs INDEL)
# ------------------------------------------------------------------
RAW_SNP_VCFS = expand(
    os.path.join(VCF_DIR, "{sample}.raw_snps.vcf"),
    sample=SAMPLES,
)
RAW_SNP_VCF_IDXS = [v + ".idx" for v in RAW_SNP_VCFS]

RAW_INDEL_VCFS = expand(
    os.path.join(VCF_DIR, "{sample}.raw_indels.vcf"),
    sample=SAMPLES,
)
RAW_INDEL_VCF_IDXS = [v + ".idx" for v in RAW_INDEL_VCFS]


# ------------------------------------------------------------------
# Step 6 — Filter SNPs
# ------------------------------------------------------------------
FILTERED_SNP_VCFS = expand(
    os.path.join(VCF_DIR, "{sample}.filtered_snps.vcf"),
    sample=SAMPLES,
)
FILTERED_SNP_VCF_IDXS = [v + ".idx" for v in FILTERED_SNP_VCFS]


# ------------------------------------------------------------------
# Step 7 — Filter INDELs
# ------------------------------------------------------------------
FILTERED_INDEL_VCFS = expand(
    os.path.join(VCF_DIR, "{sample}.filtered_indels.vcf"),
    sample=SAMPLES,
)
FILTERED_INDEL_VCF_IDXS = [v + ".idx" for v in FILTERED_INDEL_VCFS]


# ------------------------------------------------------------------
# Step 8 — Exclude Filtered Variants (PASS-only for BQSR)
# ------------------------------------------------------------------
BQSR_SNP_VCFS = expand(
    os.path.join(VCF_DIR, "{sample}.bqsr_snps.vcf"),
    sample=SAMPLES,
)
BQSR_SNP_VCF_IDXS = [v + ".idx" for v in BQSR_SNP_VCFS]

BQSR_INDEL_VCFS = expand(
    os.path.join(VCF_DIR, "{sample}.bqsr_indels.vcf"),
    sample=SAMPLES,
)
BQSR_INDEL_VCF_IDXS = [v + ".idx" for v in BQSR_INDEL_VCFS]


# ------------------------------------------------------------------
# Include rules
# ------------------------------------------------------------------
include: "rules/download_fastq.smk"
include: "rules/reference.smk"
include: "rules/align.smk"
include: "rules/sort_bam.smk"
include: "rules/metrics.smk"
include: "rules/mark_duplicates.smk"
include: "rules/index_bam.smk"
include: "rules/haplotypecaller.smk"
include: "rules/select_variants.smk"
include: "rules/filter_snps.smk"
include: "rules/filter_indels.smk"
include: "rules/exclude_filtered_variants.smk"


rule all:
    input:
        config["samples_tsv"],
        FASTQ_R1,
        FASTQ_R2,
        REF_FA,
        CANON_FA,
        REF_FAIDX,
        REF_DICT,
        BWA_INDEX,
        SORTED_BAMS,
        METRICS,
        DEDUP_BAMS,
        DEDUP_METRICS,
        DEDUP_BAI,
        RAW_VCFS,
        RAW_VCF_IDXS,
        RAW_SNP_VCFS,
        RAW_SNP_VCF_IDXS,
        RAW_INDEL_VCFS,
        RAW_INDEL_VCF_IDXS,
        FILTERED_SNP_VCFS,
        FILTERED_SNP_VCF_IDXS,
        FILTERED_INDEL_VCFS,
        FILTERED_INDEL_VCF_IDXS,
        BQSR_SNP_VCFS,
        BQSR_SNP_VCF_IDXS,
        BQSR_INDEL_VCFS,
        BQSR_INDEL_VCF_IDXS