import os
from pathlib import Path

configfile: "config.yaml"


def read_accessions(path: str) -> list[str]:
    with open(path) as f:
        return [l.strip() for l in f if l.strip() and not l.startswith("#")]


# ------------------------------------------------------------------
# Inputs: ONLY config.yaml + accessions.txt are required on a clean clone
# ------------------------------------------------------------------
ACCESSIONS = read_accessions(config["accessions_file"])
SAMPLES = ACCESSIONS  # sample IDs == run accessions in this project


# ------------------------------------------------------------------
# FASTQs and samples table (generated by scripts/download_fastq.sh)
# ------------------------------------------------------------------
FASTQ_R1 = expand(
    "{fastq_dir}/{sample}_1.fastq.gz",
    fastq_dir=config["fastq_dir"],
    sample=SAMPLES,
)
FASTQ_R2 = expand(
    "{fastq_dir}/{sample}_2.fastq.gz",
    fastq_dir=config["fastq_dir"],
    sample=SAMPLES,
)


# ------------------------------------------------------------------
# Reference (raw + canonical)
# ------------------------------------------------------------------
REF_DIR = config["reference_dir"]
REF_FILE = config["references"][0].replace(".gz", "")
CANON_FILE = config.get("reference_canonical", [REF_FILE])[0]

REF_FA = os.path.join(REF_DIR, REF_FILE)
CANON_FA = os.path.join(REF_DIR, CANON_FILE)

REF_FAIDX = [REF_FA + ".fai", CANON_FA + ".fai"]
REF_DICT = [
    os.path.join(REF_DIR, Path(REF_FILE).with_suffix("").with_suffix(".dict").name),
    os.path.join(REF_DIR, Path(CANON_FILE).with_suffix("").with_suffix(".dict").name),
]


# ------------------------------------------------------------------
# BAM outputs
# ------------------------------------------------------------------
BAM_DIR = config.get("bam_dir", "results/bam")
Path(BAM_DIR).mkdir(parents=True, exist_ok=True)

SAMS = expand(
    os.path.join(BAM_DIR, "{sample}.sam"),
    sample=SAMPLES,
)

SORTED_BAMS = expand(
    os.path.join(BAM_DIR, "{sample}.sorted.bam"),
    sample=SAMPLES,
)


# ------------------------------------------------------------------
# Metrics outputs
# ------------------------------------------------------------------
METRICS_DIR = config.get("metrics_dir", "results/metrics")
Path(METRICS_DIR).mkdir(parents=True, exist_ok=True)

METRICS = expand(
    os.path.join(METRICS_DIR, "{sample}.alignment_metrics.txt"),
    sample=SAMPLES,
)


# ------------------------------------------------------------------
# Dedup + index outputs (last common step)
# ------------------------------------------------------------------
DEDUP_DIR = config.get("dedup_dir", "results/dedup")
Path(DEDUP_DIR).mkdir(parents=True, exist_ok=True)

DEDUP_BAMS = expand(
    os.path.join(DEDUP_DIR, "{sample}.dedup.bam"),
    sample=SAMPLES,
)
DEDUP_METRICS = expand(
    os.path.join(DEDUP_DIR, "{sample}.metrics.txt"),
    sample=SAMPLES,
)
DEDUP_BAI = expand(
    os.path.join(DEDUP_DIR, "{sample}.dedup.bai"),
    sample=SAMPLES,
)


# ------------------------------------------------------------------
# Include rules (stop at BAM index)
# ------------------------------------------------------------------
include: "rules/download_fastq.smk"
include: "rules/reference.smk"
include: "rules/align.smk"
include: "rules/sort_bam.smk"
include: "rules/metrics.smk"
include: "rules/mark_duplicates.smk"
include: "rules/index_bam.smk"


rule all:
    input:
        # Generated early; useful for inspection, but no longer used at parse-time:
        config["samples_tsv"],
        FASTQ_R1,
        FASTQ_R2,
        REF_FA,
        CANON_FA,
        REF_FAIDX,
        REF_DICT,
        SORTED_BAMS,
        METRICS,
        DEDUP_BAMS,
        DEDUP_METRICS,
        DEDUP_BAI
